version: 2.1
jobs:
  compile:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: sudo apt-get install -y ccache bc bash git-core gnupg build-essential zip curl make automake autogen autoconf autotools-dev libtool shtool python m4 gcc libtool zlib1g-dev dash pigz gcc-aarch64-linux-gnu flex libssl-dev
      - checkout
      - run: wget https://raw.githubusercontent.com/alanndz/my_scripts/master/kernel_lavender_ci.sh
      - run: chmod +x kernel_lavender_ci.sh
      - run: bash kernel_lavender_ci.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
 
